service: quotes
 
provider:
  name: aws
  runtime: python3.9
  region: ap-southeast-1
  memorySize: 128

plugins:
  - serverless-wsgi

custom:
  wsgi:
    app: app.app
    packRequirements: false

functions:
  app:
    handler: wsgi_handler.handler
    url: true